# include basic settings for the models and the learning process


# dataset settings for the original dataset and the corresponding multimodal data processor
data:
  datasource_name: GSM8K
  datasource_path: data # path of the source data

  data_name: GSM8K
  data_path: data

  # One may need to download the GSM8k dataset
  datasource_download_url: null # mainly for website

  
environment:

  # The name of the project
  project_name: ICLR 
  
  # Fix the see for reproducible
  seed: 15
  
model:

  model_name: gpt-4 # "gpt-3.5-turbo","gpt-4"
  model_type: gpt

  prompt_type: zeroshot_cot

  authorization_env_path: ./.env

  num_trees: 1
  n_iteration: 3
  aggregation_type: best_first
  
  generation_settings:
    temperature: 0.7
    max_tokens: 1000
    stop: null 
    top_p: 0.7

  tree_settings:
    n_child_nodes: 2
    max_leaves: 20
    max_depth: 5
    min_leaf_thought_score: 0.1
    max_leaf_thought_score: 1.1
    min_thoughts_similarity: 0.9
    max_thoughts_score_diff: 0.1

  pretrained_models_path: experiments/pretrained_models

trainer:

logging:
  # path where to save, empty for no saving
  experiment_path: experiments
  checkpoint_path: experiments/checkpoints
  result_path: experiments/results
  logging_path: experiments/loggings
  visualization_path: experiments/visualizations

evaluation:


  # set the hyper parameters for performance
  performance:
   




