data:
 
  data_name: GSM8K
  data_path: data

  # One may need to download the GSM8k dataset
  download_url: null

  extractor:
    purpose: groundtruth
    style: re
  
environment:

  # The name of the project
  project_name: ICLR 
  
  # Fix the see for reproducible
  seed: 15
  
model:

  model_name: gpt-3.5-turbo # "gpt-3.5-turbo","gpt-4"
  model_type: gpt

  prompt_type: zeroshot

  authorization_path: ./.env

  generation_settings:
    temperature: 0.7
    max_tokens: 1000
    # n here is n_completions_per_prompt
    n: 1
    stop: null 

  thought_structure:
    num_next_steps: 1
    max_length: 4
    max_stops: 1
    min_thought_similarity: 0.9
    max_score_diff: 0.1
    min_stop_score: 0.1
    max_stop_score: 1.0

    model_name: gpt-3.5-turbo # "gpt-3.5-turbo","gpt-4"
    model_type: gpt
    generation_settings:
      temperature: 0.7
      max_tokens: 1000
      # n here is n_completions_per_prompt
      n: 1
      stop: null 


  pretrained_models_path: experiments/pretrained_models


trainer:


logging:
  # path where to save, empty for no saving
  experiment_path: experiments
  checkpoint_path: experiments/checkpoints
  result_path: experiments/results
  logging_path: experiments/loggings
  visualization_path: experiments/visualizations

evaluation:
  
  # basic, llm
  style: basic

  extractor:
    purpose: result
    # re, llm
    style: llm

   




