# include basic settings for the models and the learning process


# dataset settings for the original dataset and the corresponding multimodal data processor
data:
  datasource_name: GSM8K
  datasource_path: data # path of the source data

  data_name: GSM8K
  data_path: data

  # One may need to download the GSM8k dataset
  datasource_download_url: null
  
environment:

  # The name of the project
  project_name: ICLR 
  
  # Fix the see for reproducible
  seed: 15

  
  
model:

  model_name: gpt-3.5-turbo # "gpt-3.5-turbo","gpt-4"
  model_type: gpt

  prompt_type: zeroshot_cot

  authorization_env_path: ./.env
  
  generation_settings:
    temperature: 0.7
    max_tokens: 1000
    # n here is n_completions_per_prompt
    n: 1
    stop: null 

  tree_settings:
    num_leaves: 6
    max_depth: 4
    min_leaf_thought_score: 0.3
    max_leaf_thought_score: 0.9
    min_thoughts_similarity: 0.6
    max_thoughts_score_diff: 0.3

  pretrained_models_path: experiments/pretrained_models

trainer:


logging:
  # path where to save, empty for no saving
  experiment_path: experiments
  checkpoint_path: experiments/checkpoints
  result_path: experiments/results
  logging_path: experiments/loggings
  visualization_path: experiments/visualizations

evaluation:

  n_shots: 5

  # set the hyper parameters for performance
  performance:




