
# The basic settings for the thought structure
thought_structure:
    num_next_steps: 1
    # Note that the length computation includes the root node
    # Set the length to be longer to reach the final solution
    # and the chain growth in the thought structure will be stopped 
    # when reach the solution is reached in the node.
    max_length: 20
    max_stops: 1
    min_thought_similarity: null # 0.95
    max_score_difference: 0.1 # 0.1



