data:
 
  data_name: SVAMP
  data_path: data

  # One may need to download the SVAMP dataset
  download_url: null
 
  
environment:

  # The name of the project
  project_name: LLMPE 
  
  # Fix the see for reproducible
  seed: 15
  
model:

    # "gpt-3.5-turbo","gpt-4",
  # gpt-4-1106-preview, gpt-4-0125-preview
  model_name: gpt-4-1106-preview
  model_type: gpt

  prompt_type: zeroshot_cot 
  
  authorization_path: ./.env

  generation_settings:
    temperature: 0.7
    max_tokens: 1000
    # n here is n_completions_per_prompt
    n: 1
    stop: null 

  pretrained_models_path: experiments/pretrained_models


train:


logging:
  # path where to save, empty for no saving
  experiment_path: experiments
  checkpoint_path: experiments/checkpoints
  result_path: experiments/results
  logging_path: experiments/loggings
  visualization_path: experiments/visualizations

evaluation:
  
  # basic, llm
  style: basic

  extractor:
    purpose: result
    style: llm

   




